{% set name = "resample" %}
{% set version = "1.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/resample-{{ version }}.tar.gz
  sha256: ff66c9142cae46317fb8b58e7acf59c963721e4f2a1505830cce99b57e78f091

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip !=22.1.0
  run:
    - python
    - numpy >=1.21
    - scipy >=1.10

test:
  source_files:
    - tests
  requires:
    - pytest
    - pip
  imports:
    - resample
  commands:
    - python -m pytest tests
    - pip check

about:
  home: https://github.com/scikit-hep/resample
  summary: Tools for randomization-based inference in Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dsaxton
    - HDembinski
    - conda-forge/scikit-hep
