{% set name = "resample" %}
{% set version = "1.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/resample-{{ version }}.tar.gz
  sha256: 92071cb0c2c1f7429e6a21ae3073bf3e69b11573a0dfaa04429737931ad4ab82

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip !=22.1.0
    - python >=3.7
  run:
    - numpy >=1.19
    - python >=3.7
    - scipy >=1.5

test:
  requires:
    - pytest
    - pip
  imports:
    - resample
  requires:
    - pip
  commands:
    - python -m pytest tests
    - pip check

about:
  home: https://github.com/scikit-hep/resample
  summary: Tools for randomization-based inference in Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dsaxton
    - HDembinski
